### ISSUE TITLE
Over query limit

### ISSUE THREAD

**Issue by dionsnoeijen** [symphonists/maplocationfield#12]
The google geocode api returns:

variable: $response line 74 of field.maplocation.php:

```
stdClass Object ( [results] => Array ( ) [status] => OVER_QUERY_LIMIT )
```

But when I lookup the url directly, everything is working fine with a status: "OK":
http://maps.googleapis.com/maps/api/geocode/json?address=veldhoven%2CNL&sensor=false

I don't know what's going on. I haven't used it more than 10 times before it was working.

**Comment by nitriques** [comment]
With the new release, an API key is needed, which should fix this.
