### ISSUE TITLE
Output Performance

### ISSUE THREAD

**Issue by animaux** [symphonists/maplocationfield#17]
A rather simple output of 5655 entries with only **map location field** lat/lng data takes 8.5s for the XML to be created, even though I have already commented out the output of the `<map/>` element containing `centre` and `zoom` attributes.

**Comment by animaux** [comment]
`geo	7.4136 s from 9 queries`

**Comment by nitriques** [comment]
@animaux What's the timing without the field ?

**Comment by animaux** [comment]
I’ve kind of _overcome_ the problem with the `cacheable_datasource` extension. 

`geo` is the only field in the DS, strangely removing it results in:

`geo 7.0831 s from 5 queries`

**Comment by animaux** [comment]
I think you are right : )

```
Engine Initialisation	0.0168 s
Page creation started	0.0389 s
XML Built	7.8636 s
Page Built	7.8799 s
XML Generation	0.1831 s
XSLT Transformation	0.0643 s
Page creation complete	8.1663 s
```

**Comment by animaux** [comment]
Oh, hang on. I’ve meant to send this:

```
Total Database Queries	24
Slow Queries (> 0.09s)	0
Total Time Spent on Queries	0.2598 s
Time Triggering All Events	0.0000 s
Time Running All Data Sources	6.8104 s
XML Generation	0.1697 s
XSLT Transformation	0.0483 s
Output Creation Time	0.0000 s
Total Memory Usage	16.78 MB
```

**Comment by nitriques** [comment]
Is the DB server the same machine as the webserver ? It's telling me it's a transport problems if there are no "Slow queries". And the "Total Time Spent on Queries	0.2598 s".

**Comment by animaux** [comment]
@nitriques yes, same server.

**Comment by michael-e** [comment]
How many lines of XML are created? Actually creating the XML is often the bottleneck, IMHO.

**Comment by animaux** [comment]
5660 entries, each like this:

        <entry id="627">
            <geo latitude="50.9802318997855" longitude="11.330360590274" />
        </entry>

**Comment by michael-e** [comment]
That might be the problem. In one of my projects I save "ready-made" XML to the database, so I can add it quickly without the need to create it from scratch. Symphony creates XML by creating objects first, and this is rather slow for large datasets.

If you use the Cacheable Datasource extension, it's the same: The cached XML is ready to be inserted.

You might think about using a cronjob to periodically refresh the DS cache (by calling a special page, for example) **before a visitor needs it**. :-)

**Comment by animaux** [comment]
Thanks Michael. That’s a very nice idea with the crojob!

**Comment by nitriques** [comment]
Hum the timers label are a bit misleading then ;) Cron jobs or use a free provider that will cache your DS for you, i.e. http://uptimerobot.com/

I would also try to create a special page that could be fetch usign ajax ? Maybe that will be easier to manage in the end.

So I'll close the issue since it more of a core issue.

**Comment by animaux** [comment]
Ok, thanks @michael-e and @nitriques, that info is really helpful!

**Comment by nitriques** [comment]
Strangely, I had the same problem with others yesterday. I'll see what can be done.
